# -*- coding: utf-8 -*-
"""Geek Academy_exercícios Sec.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/marcela-medeiros/b94bb7bd0092cf3a7954ad203cf69b86/geek-academy_exerc-cios-sec-4.ipynb

**Resoluções dos exercícios da Geek University - Seção 4.**
Disponível em: [Geek Academy](https://www.udemy.com/course/curso-de-programacao-em-python-do-basico-ao-avancado/)

1.
"""

num = int(input('Digite um número inteiro:'))
print(num)

"""2."""

num = float(input('Digite um número real:'))
print (num)

"""3."""

one = int(input("Digite um número  "))
two = int (input("Digite outro número  "))
three = int(input("Digite um último número  "))

sum = one + two + three

print (sum)

"""4."""

num = int(input('Digite um número:  '))
power = num**2

print(power)

"""5."""

num = float (input(" Digite um número:   "  ))
quinta = num/5

print(quinta)

"""6."""

tCelsius = float (input("Insira a temperatura em graus Celsius:   "))
tFarenheit = tCelsius*(9.0/5.0)+32

print("A temperatura em graus Farenheit é:   ", tFarenheit)

"""7."""

tFarenheit = float(input(" Insira. e temperatura em graus Farenheit:  "))
tCelsius = 5.0*(tFarenheit-32.0)/9.0

print("A temperatura em graus Celsius é:   ", tCelsius)

"""8."""

tKelvin = float(input("Insira a temperatura em graus Kelvin:  "))
tCelsius = tKelvin - 273.15

print("A temperatura em graus Celsius é:  ", tCelsius)

"""9."""

tCelsius = float(input("Insira a temperatura em graus Celsius:  "))
tKelvin = tCelsius + 273.15

print("A temperatura em graus Kelvin é:  ", tKelvin)

"""10."""

km= float(input("Insira a velocidade em kilometros:  "))
metros = km/3.6

print ("A velocidade em metros por segundo é:",metros)

"""11."""

metros = float(input("Insira a velocidade em metros por segundo:  "))
km = metros * 3.6

print(km)

"""12."""

milhas = float(input("Insira a distância em milhas:  "))
quilometros = 1.61 * milhas

print ("O valor em kilometros corresponde a:", quilometros)

"""13."""



"""14."""



"""37."""

prod = float(input("Informe o valor do produto em reais:  "))
desc = prod -  (prod*0.12)

print("O valor do produto com desconto é de:   ", desc)

"""38."""

funcionario = input("Nome do funcionário:  ")
salario = float(input("Informe o valor do salário   "))
aumento = salario + (salario * 0.25)
print ("Bem - vindo ao Sigstaff,",funcionario, "!", "O valor da sua remuneração é: ", aumento)

"""39."""

premio = 780000
concurso = "O prêmio final do concurso, no valor de", "R$", premio, "será dividido entre os seguintes ganhadores:"
gan1 = premio * 0.46
gan2 = (premio - gan1) * 0.32
gan3 = premio - gan1 - gan2

print(f"O primeiro ganhador levará um prêmio de R$ {gan1: ,.2f}")
print (f"O segundo ganhador levará um prêmio de R$ {gan2: ,.2f}")
print (f"O terceiro ganhador levará um prêmio de R${gan3: ,.2f}")

